services:
  postgres:
    image: postgres:16-alpine
    container_name: polylivre-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: ${APPLICATION_NAME}
    ports:
      - "${BACKEND_END_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_VALIDITY: ${JWT_VALIDITY}
      APP_PASSWORD: ${APP_PASSWORD}
      FRONT_END_ORIGIN: ${FRONT_END_ORIGIN}
      RP_NAME: ${RP_NAME}
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started

  mailpit:
    image: axllent/mailpit
    container_name: polylivre-mail
    ports:
      - "${MAIL_PORT}:1025"
      - "8025:8025"
    platform: linux/amd64

volumes:
  postgres_data:
