spring:
  application.name: poly-livre-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/polylivredb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none
  mail:
    host: localhost
    port: 1025
    username: null
    password: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  jackson:
    default-property-inclusion: non_null

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}
  validity: 3600 # 1 hour
  algorithm: EC
  issuer: backend-poly-livre

logging.level:
  com.poly.livre.backend: DEBUG

webauthn:
  rp-id: localhost
  rp-name: Liprerie
  origin: http://localhost:3000
