spring:
  application.name: "${APPLICATION_NAME:poly-livre-backend}"
  app:
    password: "${APP_PASSWORD:IA2R_Owners}"
  datasource:
    url: "jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:poly_livre_db}"
    username: "${POSTGRES_USER:username}"
    password: "${POSTGRES_PASSWORD:password}"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: "${HOST:localhost}"
    port: "${MAIL_PORT:1025}"
    username: null
    password: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  jackson:
    default-property-inclusion: non_null

jwt:
  privateKey: "${JWT_PRIVATE_KEY:MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgO8Nm9Rv9Kz2J7TLtdoIjHDL5Mo4WCWS0ixQfGwxBqGahRANCAAQpbN6OWGmhJFO99NzDu89U2HjIFzIDw8417Y7LFqTJ3+FJXv99EDPjHfJhZKkuD66FEjUflmadCFHdy1dkss1j}"
  publicKey: "${JWT_PUBLIC_KEY:MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKWzejlhpoSRTvfTcw7vPVNh4yBcyA8PONe2Oyxakyd/hSV7/fRAz4x3yYWSpLg+uhRI1H5ZmnQhR3ctXZLLNYw==}"
  validity: 3600
  algorithm: "${JWT_ALGORITHM:EC}"
  issuer: "${ISSUER:backend-poly-livre}"

logging.level:
  com.poly.livre.backend: DEBUG

webauthn:
  rp-id: "${HOST:localhost}"
  rp-name: "${RP_NAME:Liprerie}"
  origin: "${FRONT_END_ORIGIN:http://localhost:3000}"
